version: '3'
services:

    # flask api/backend
    api:
        container_name: api
        restart: always
        ports:
            - "5000:5000"
        build:
            context: ./
            dockerfile: ./docker/Dockerfile.dev.flask
        volumes:
            - ./lib:/api/lib
            - ./api.py:/api/api.py
            - ./static:/api/static
            - ./templates:/api/templates
        networks:
            - backend
    
    # react UI/frontend
    client:
        stdin_open: true
        container_name: client
        restart: always
        ports:
            - "3000:3000"
        build:
            context: ./
            dockerfile: ./docker/Dockerfile.dev.react
        volumes:
            - ./web/src/:/web/src/
            - ./web/public/:/web/public/
        depends_on: 
            - "api"
        environment:
            - NODE_ENV=development
        networks:
            - backend

networks:
    backend:
        driver: bridge